import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://127.0.0.1:5173/day/2025-04-23');
  await page.getByRole('button', { name: '+ Add Habit' }).click();
  await page.getByRole('textbox', { name: 'Enter habit name' }).click();
  await page.getByRole('textbox', { name: 'Enter habit name' }).fill('testas 1');
  await page.getByRole('button', { name: 'Add Habit', exact: true }).click();
  await page.getByRole('button', { name: '+ Add Habit' }).click();
  await page.getByRole('textbox', { name: 'Enter habit name' }).click();
  await page.getByRole('textbox', { name: 'Enter habit name' }).fill('Testas 2');
  await page.getByRole('button', { name: 'Add Habit', exact: true }).click();
  await page.getByRole('button', { name: '+ Add Habit' }).click();
  await page.getByRole('textbox', { name: 'Enter habit name' }).click();
  await page.getByRole('textbox', { name: 'Enter habit name' }).fill('testas 3');
  await page.getByRole('button', { name: 'Add Habit', exact: true }).click();
  await page.getByRole('checkbox').first().check();
  await page.getByRole('button', { name: '← Previous' }).click();
  await page.getByRole('button', { name: '← Previous' }).click();
  await page.getByRole('button', { name: '← Previous' }).click();
  await page.getByRole('checkbox').nth(2).check();
  await page.getByRole('button', { name: 'Next →' }).click();
  await page.getByRole('checkbox').nth(2).check();
  await page.getByRole('button', { name: 'Next →' }).click();
  await page.getByRole('checkbox').nth(2).check();
  await page.getByRole('button', { name: 'Edit Icon' }).nth(1).click();
  await page.getByRole('button', { name: 'Stop' }).click();
  await page.locator('body').click();
  await page.getByRole('button', { name: 'Next →' }).click();
});